//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct AddMessageParamModel: APIModel {
    public var sessionId: Int64

    /**
     * 消息来源用于区分是用户的还是botanist
     */
    public var from: MessageFrom

    /**
     * chatbot组件只提供通用的text, customize类型需要结合各种app-service定义来解析再次解析MessageContent.text
     */
    public var messageContent: MessageContentModel

    /**
     * 本条消息相关itemId（没有就不传）
     */
    public var itemIds: [Int64]?

    /**
     * 本条消息相关itemType（没有就不传）
     */
    public var itemType: String?

    /**
     * 本条消息相关的物种uid（没有就不传）
     */
    public var uid: String?

    public var extraFields:  [String: AnyCodable]?

    enum CodingKeys: String, CodingKey {
        case sessionId = "session_id"

        case from = "from"

        case messageContent = "message_content"

        case itemIds = "item_ids"

        case itemType = "item_type"

        case uid = "uid"

        case extraFields = "extra_fields"
    }
    
    public init(
            sessionId: Int64, 
            from: MessageFrom, 
            messageContent: MessageContentModel, 
            itemIds: [Int64]? = nil, 
            itemType: String? = nil, 
            uid: String? = nil, 
            extraFields:  [String: AnyCodable]? = nil) {
        self.sessionId = sessionId
        self.from = from
        self.messageContent = messageContent
        self.itemIds = itemIds
        self.itemType = itemType
        self.uid = uid
        self.extraFields = extraFields
    }
}
