//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct ChatArgsModel: APIModel {
    /**
     * 模型名称，可以是gpt-4o, gpt-4o-mini
     */
    public var model: String

    public var maxTokens: Int

    /**
     * temperature [0.0, 1.0]
     */
    public var temperature: Double

    enum CodingKeys: String, CodingKey {
        case model = "model"

        case maxTokens = "max_tokens"

        case temperature = "temperature"
    }
    
    public init(
            model: String, 
            maxTokens: Int, 
            temperature: Double) {
        self.model = model
        self.maxTokens = maxTokens
        self.temperature = temperature
    }
}
