//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct ChatbotUpdateMessageTagsRequest: APIEncodableRequest {
    public typealias Response = ChatbotUpdateMessageTagsResponse

    public var messageId: Int64

    /**
     * 注意是直接覆盖
 空数组表示清空
     */
    public var messageTags: [String]?

    enum CodingKeys: String, CodingKey {
        case messageId = "message_id"

        case messageTags = "message_tags"
    }
    
    public init(
            messageId: Int64, 
            messageTags: [String]? = nil) {
        self.messageId = messageId
        self.messageTags = messageTags
    }
    
    public var api: String {
        "v4/chatbot/update_message_tags"
    }
    
    public var forceHttps: Bool {
        true
    }
    
    public var needAuth: Bool {
        true
    }
    
    public var mustAuth: Bool {
        true
    }
    
    public var methods: [String] {
        ["POST"]
    }
    
    public var mimeBodies: [APIMimeBody] {
        var bodies: [APIMimeBody] = []

        return bodies
    }
    
    public func parseParamater<T>(encoder: T) throws -> T.Output where T : APIEncoder {
        try encoder.encode(self)
    }
}

public struct ChatbotUpdateMessageTagsResponse: APIJSONResponse {


    public init<T>(data: T.Input, decoder: T) throws where T : APIDecoder {
        self = try decoder.decode(ChatbotUpdateMessageTagsResponse.self, from: data)
    }
}
