//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

/**
 * 获取messages
 */

public struct ChatbotFindMessageListRequest: APIEncodableRequest {
    public typealias Response = ChatbotFindMessageListResponse

    public var lastMessageId: Int64?

    public var sessionId: Int64

    public var orderBy: OrderBy

    public var languageCode: LanguageCode

    public var countryCode: String

    enum CodingKeys: String, CodingKey {
        case lastMessageId = "last_message_id"

        case sessionId = "session_id"

        case orderBy = "order_by"

        case languageCode = "language_code"

        case countryCode = "country_code"
    }
    
    public init(
            lastMessageId: Int64? = nil, 
            sessionId: Int64, 
            orderBy: OrderBy, 
            languageCode: LanguageCode, 
            countryCode: String) {
        self.lastMessageId = lastMessageId
        self.sessionId = sessionId
        self.orderBy = orderBy
        self.languageCode = languageCode
        self.countryCode = countryCode
    }
    
    public var api: String {
        "v4/chatbot/find_message_list"
    }
    
    public var forceHttps: Bool {
        true
    }
    
    public var needAuth: Bool {
        true
    }
    
    public var mustAuth: Bool {
        true
    }
    
    public var methods: [String] {
        ["GET"]
    }
    
    public var mimeBodies: [APIMimeBody] {
        var bodies: [APIMimeBody] = []

        return bodies
    }
    
    public func parseParamater<T>(encoder: T) throws -> T.Output where T : APIEncoder {
        try encoder.encode(self)
    }
}

public struct ChatbotFindMessageListResponse: APIJSONResponse {
    public var messageList: [MessageModel]

    enum CodingKeys: String, CodingKey {
        case messageList = "message_list"
    }

    public init<T>(data: T.Input, decoder: T) throws where T : APIDecoder {
        self = try decoder.decode(ChatbotFindMessageListResponse.self, from: data)
    }
}
