//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

/**
 * 获取消息
 */

public struct ChatbotGetMessagesRequest: APIEncodableRequest {
    public typealias Response = ChatbotGetMessagesResponse

    public var languageCode: LanguageCode

    public var countryCode: String

    public var messageIds: [Int64]

    enum CodingKeys: String, CodingKey {
        case languageCode = "language_code"

        case countryCode = "country_code"

        case messageIds = "message_ids"
    }
    
    public init(
            languageCode: LanguageCode, 
            countryCode: String, 
            messageIds: [Int64]) {
        self.languageCode = languageCode
        self.countryCode = countryCode
        self.messageIds = messageIds
    }
    
    public var api: String {
        "v4/chatbot/get_messages"
    }
    
    public var forceHttps: Bool {
        true
    }
    
    public var needAuth: Bool {
        true
    }
    
    public var mustAuth: Bool {
        true
    }
    
    public var methods: [String] {
        ["GET"]
    }
    
    public var mimeBodies: [APIMimeBody] {
        var bodies: [APIMimeBody] = []

        return bodies
    }
    
    public func parseParamater<T>(encoder: T) throws -> T.Output where T : APIEncoder {
        try encoder.encode(self)
    }
}

public struct ChatbotGetMessagesResponse: APIJSONResponse {
    public var messageList: [MessageModel]

    enum CodingKeys: String, CodingKey {
        case messageList = "message_list"
    }

    public init<T>(data: T.Input, decoder: T) throws where T : APIDecoder {
        self = try decoder.decode(ChatbotGetMessagesResponse.self, from: data)
    }
}
