//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct ChatbotGenerateImageRequest: APIEncodableRequest {
    public typealias Response = ChatbotGenerateImageResponse

    /**
     * 生成图片的提示文本
     */
    public var prompt: String

    /**
     * 生成的图片数量：1 ~ 4
     */
    public var sampleCount: Int

    /**
     * 图片的宽高比。默认值为“1:1”
     */
    public var aspectRatio: ImageAspectRatio?

    enum CodingKeys: String, CodingKey {
        case prompt = "prompt"

        case sampleCount = "sample_count"

        case aspectRatio = "aspect_ratio"
    }
    
    public init(
            prompt: String, 
            sampleCount: Int, 
            aspectRatio: ImageAspectRatio? = nil) {
        self.prompt = prompt
        self.sampleCount = sampleCount
        self.aspectRatio = aspectRatio
    }
    
    public var api: String {
        "v4/chatbot/generate_image"
    }
    
    public var forceHttps: Bool {
        true
    }
    
    public var needAuth: Bool {
        true
    }
    
    public var mustAuth: Bool {
        true
    }
    
    public var methods: [String] {
        ["POST"]
    }
    
    public var mimeBodies: [APIMimeBody] {
        var bodies: [APIMimeBody] = []

        return bodies
    }
    
    public func parseParamater<T>(encoder: T) throws -> T.Output where T : APIEncoder {
        try encoder.encode(self)
    }
}

public struct ChatbotGenerateImageResponse: APIJSONResponse {
    public var results: [ImagenResultModel]

    enum CodingKeys: String, CodingKey {
        case results = "results"
    }

    public init<T>(data: T.Input, decoder: T) throws where T : APIDecoder {
        self = try decoder.decode(ChatbotGenerateImageResponse.self, from: data)
    }
}
