//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct ChatbotCreateSessionRequest: APIEncodableRequest {
    public typealias Response = ChatbotCreateSessionResponse

    /**
     * 本次会话的type，各个产品自己定义，可以用来区分不同地方进入的会话
     */
    public var sessionType: String

    enum CodingKeys: String, CodingKey {
        case sessionType = "session_type"
    }
    
    public init(
            sessionType: String) {
        self.sessionType = sessionType
    }
    
    public var api: String {
        "v4/chatbot/create_session"
    }
    
    public var forceHttps: Bool {
        true
    }
    
    public var needAuth: Bool {
        true
    }
    
    public var mustAuth: Bool {
        true
    }
    
    public var methods: [String] {
        ["POST"]
    }
    
    public var mimeBodies: [APIMimeBody] {
        var bodies: [APIMimeBody] = []

        return bodies
    }
    
    public func parseParamater<T>(encoder: T) throws -> T.Output where T : APIEncoder {
        try encoder.encode(self)
    }
}

public struct ChatbotCreateSessionResponse: APIJSONResponse {
    public var sessionId: Int64

    enum CodingKeys: String, CodingKey {
        case sessionId = "session_id"
    }

    public init<T>(data: T.Input, decoder: T) throws where T : APIDecoder {
        self = try decoder.decode(ChatbotCreateSessionResponse.self, from: data)
    }
}
