//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

/**
 * 当MessageType 为IMAGE 时，text json的model
 */
public struct ImageMessageContentModel: APIModel {
    /**
     * 图片的url
     */
    public var url: String

    /**
     * 图片itemId
     */
    public var itemId: Int64

    public var itemType: String

    public var text: String?

    public var photoFrom: Int?

    public var shootAt: Date?

    enum CodingKeys: String, CodingKey {
        case url = "url"

        case itemId = "item_id"

        case itemType = "item_type"

        case text = "text"

        case photoFrom = "photo_from"

        case shootAt = "shoot_at"
    }
    
    public init(
            url: String, 
            itemId: Int64, 
            itemType: String, 
            text: String? = nil, 
            photoFrom: Int? = nil, 
            shootAt: Date? = nil) {
        self.url = url
        self.itemId = itemId
        self.itemType = itemType
        self.text = text
        self.photoFrom = photoFrom
        self.shootAt = shootAt
    }
}
