//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct ImagenResultModel: APIModel {
    /**
     * base64 编码的生成图片
     */
    public var imageBase64: String

    /**
     * 生成的图片的类型
     */
    public var mimeType: String

    /**
     * 如果您使用的是支持提示增强功能的模型，回答中还会包含一个 prompt 字段，其中包含用于生成的增强型提示
     */
    public var prompt: String?

    enum CodingKeys: String, CodingKey {
        case imageBase64 = "image_base64"

        case mimeType = "mime_type"

        case prompt = "prompt"
    }
    
    public init(
            imageBase64: String, 
            mimeType: String, 
            prompt: String? = nil) {
        self.imageBase64 = imageBase64
        self.mimeType = mimeType
        self.prompt = prompt
    }
}
