//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct MessageContentModel: APIModel {
    public var messageType: MessageType

    public var text: String

    enum CodingKeys: String, CodingKey {
        case messageType = "message_type"

        case text = "text"
    }
    
    public init(
            messageType: MessageType, 
            text: String) {
        self.messageType = messageType
        self.text = text
    }
}
