//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct MessageModel: APIModel {
    public var messageId: Int64?

    public var sessionId: Int64

    /**
     * 消息来源用于区分是用户的还是chatbot的
     */
    public var from: MessageFrom

    /**
     * chatbot组件只提供通用的text, customize类型需要结合各种app-service定义来解析再次解析MessageContent.text
     */
    public var messageContent: MessageContentModel

    /**
     * 额外信息，各个产品自己定义，自己解析，组件不解析
     */
    public var extraFields:  [String: AnyCodable]?

    /**
     * 如 是否喜欢，是否有用等
     */
    public var messageTags: [String]?

    /**
     * 这条消息的发送时间（其实就是创建时间）
     */
    public var sendAt: Date

    enum CodingKeys: String, CodingKey {
        case messageId = "message_id"

        case sessionId = "session_id"

        case from = "from"

        case messageContent = "message_content"

        case extraFields = "extra_fields"

        case messageTags = "message_tags"

        case sendAt = "send_at"
    }
    
    public init(
            messageId: Int64? = nil, 
            sessionId: Int64, 
            from: MessageFrom, 
            messageContent: MessageContentModel, 
            extraFields:  [String: AnyCodable]? = nil, 
            messageTags: [String]? = nil, 
            sendAt: Date) {
        self.messageId = messageId
        self.sessionId = sessionId
        self.from = from
        self.messageContent = messageContent
        self.extraFields = extraFields
        self.messageTags = messageTags
        self.sendAt = sendAt
    }
}
