//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

/**
 * Google speech_to_text 返回的时间点信息。@see https://cloud.google.com/text-to-speech/docs/reference/rest/v1beta1/text/synthesize#Timepoint
 */
public struct TimepointModel: APIModel {
    public var markName: String

    public var timeSeconds: String

    enum CodingKeys: String, CodingKey {
        case markName = "mark_name"

        case timeSeconds = "time_seconds"
    }
    
    public init(
            markName: String, 
            timeSeconds: String) {
        self.markName = markName
        self.timeSeconds = timeSeconds
    }
}
