//
// Generated code, do not modify.
// Generated by i18N/generate.py
//

import Foundation

extension GLMPLanguage {

    // MARK: - Common
    static let common_appname = "FaceFlow"
    static let common_next = "Next"
    static let common_get_started = "Get Started"
    static let common_continue = "Continue"
    static let common_skip = "Skip"
    static let common_vocal_bass = "Bass"
    static let common_vocal_bari = "Baritone"
    static let common_vocal_tenor = "Tenor"
    static let common_vocal_alto = "Alto"
    static let common_vocal_mezzo = "Mezzo"
    static let common_vocal_sporano = "Soprano"
    static let common_done = "Done"

    // MARK: - Onboarding
    static let onboarding_start_title = "Every song is yours to master"
    static let onboarding_start_subtitle = "Personalized tunes that highlight your distinct voice"

    // MARK: - Onboarding_q1
    static let onboarding_q1_title_music_kind = "What kind of music do you sing to"
    static let onboarding_q1_option_pop = "Pop"
    static let onboarding_q1_option_rock = "Rock"
    static let onboarding_q1_option_hiphop = "Hip-Hop"
    static let onboarding_q1_option_rnb = "R&B"
    static let onboarding_q1_option_country = "Country"
    static let onboarding_q1_option_jazz = "Jazz"
    static let onboarding_q1_option_classical = "Classical"
    static let onboarding_q1_option_indie = "Indie"
    static let onboarding_q1_option_blues = "Blues"
    static let onboarding_q1_option_latin = "Latin"
    static let onboarding_q1_option_gospel = "Gospel"
    static let onboarding_q1_option_other = "Other"

    // MARK: - Onboarding_q2
    static let onboarding_q2_title_singers = "Who are your favorite singers or bands?"
    static let onboarding_q2_enter_name = "Enter Name"

    // MARK: - Onboarding_q3
    static let onboarding_q3_title_experience = "How would you describe your singing experience?"
    static let onboarding_q3_option_beginner = "I’ve never really sung before"
    static let onboarding_q3_option_intermediate = "I sing casually sometimes"
    static let onboarding_q3_option_advanced = "I’ve practiced or performed"
    static let onboarding_q3_option_professional = "I’m trained or professional"

    // MARK: - Onboarding_q4
    static let onboarding_q4_title_hope = "What goals do you hope to achieve with this app?"
    static let onboarding_q4_option_improve = "Improve my singing skills"
    static let onboarding_q4_option_enhance = "Enhance pitch and rhythm"
    static let onboarding_q4_option_reaching = "Reaching high or low notes"
    static let onboarding_q4_option_learn = "Learn new songs"
    static let onboarding_q4_option_happy = "Entertainment and relaxation"
    static let onboarding_q4_option_other = "Other"

    // MARK: - Onboarding_q5
    static let onboarding_q5_title_old = "How old are you?"
    static let onboarding_q5_option_18 = "18-24"
    static let onboarding_q5_option_24 = "24-34"
    static let onboarding_q5_option_34 = "34-44"
    static let onboarding_q5_option_45 = "45-54"
    static let onboarding_q5_option_55 = "55+"
    static let onboarding_q5_option_notsay = "Prefer not to say"

    // MARK: - Onboarding_summary
    static let onboarding_summary_title = "Find Your Unique Voice"
    static let onboarding_summary_subtitle = "Adapt any song to your range and sing with confidence"

    // MARK: - Onboarding_welcome
    static let onboarding_welcome_title = "Welcome to Your Sing Journey!"
    static let onboarding_welcome_subtitle = "Discover your voice with top hits and pro tips, all enhanced by instant AI feedback to perfect your performance."

    // MARK: - Vocal_range
    static let vocal_range_title = "Get ready to sing"
    static let vocal_range_subtitle = "Complete these 3 steps to unlock your personalized singing experience"
    static let vocal_range_title_ready = "You're Ready to Sing!"
    static let vocal_range_subtitle_ready = "Enjoy your personalized singing experience now"
    static let vocal_range_option_add_preference = "Add Your Preferences"
    static let vocal_range_option_find_range = "Find Your Vocal Range"
    static let vocal_range_option_try_sing = "Try Singing in Your Range"

    // MARK: - Find_range
    static let find_range_gender_hint = "To better estimate your vocal range, please choose your voice type"
    static let find_range_female_voice = "Female Voice"
    static let find_range_male_voice = "Male Voice"
    static let find_range_hint = "Tap the button below and read the text in your natural voice."
    static let find_range_provided_text_1 = "You say you're a mess,\nI say you're real,"
    static let find_range_provided_text_2 = "Every scar is something I feel."
    static let find_range_mm_lowest_title = "Hum the lowest note you can for 3 seconds"
    static let find_range_mm = "Mmmmmmm"
    static let find_range_ya_highest_title = "Yay the highest note you can for 3 times"
    static let find_range_ya = "Yay-Yay-Yay"
    static let find_range_tap_start = "Tap to start"
    static let find_range_retry = "Retry"
    static let find_range_next = "Next"
    static let find_range_result_title = "Your Vocal Range"

    // MARK: - Range_result
    static let range_result_title = "Your Vocal Range"
    static let range_result_test_again = "Test Again"

    // MARK: - Onboarding_review
    static let onboarding_review_help_grow = "Help us grow!"
    static let onboarding_review_subtitle = "💖 Leaving a review will encourage us a lot!"

    // MARK: - Song
    static let song_change_song = "Chnage A Song"
    static let song_start_sing = "Start Singing"

    // MARK: - Headphone_popup
    static let headphone_popup_title = "Headphones Recommended"
    static let headphone_popup_subtile = "Using headphones reduces feedback and noise, enhancing recording quality for clearer, accurate score."
    static let headphone_popup_got_it = "Got It"

    // MARK: - Settlement
    static let settlement_title = "You have finished singing this song!"
    static let settlement_notes = "Notes"
    static let settlement_timing = "Timing"
    static let settlement_x_song_finished = "Songs Finished"
    static let settlement_sing_again = "Sing Again"

    // MARK: - Home
    static let home_feedback = "Feedback"
    static let home_tool_vocal_range_finder = "Vocal Range Finder"
    static let home_tool_warmup = "Warm-up Exercise"
    static let home_tool_pitch_training = "Pitch Ear Training"
    static let home_category_pop = "Pop Music"
    static let home_category_Rock = "Rock"
    static let home_category_country = "Country & Folk"
    static let home_category_soul = "Soul & Disco"
    static let home_sing = "Sing"

    // MARK: - Warmup_intro
    static let warmup_intro_title = "Vocal warm-up"
    static let warmup_intro_feature_1 = "Listen to a given vocal exercise melody"
    static let warmup_intro_feature_2 = "Sing along to match the pitch"
    static let warmup_intro_feature_3 = "See your pitch and if you hit the right notes"
    static let warmup_intro_get_started = "Get Started"

    // MARK: - Warmup_sing
    static let warmup_sing_info = "Sing along and focus on maintaining pitch accuracy"
    static let warmup_sing_result_title = "Greate Job!"
    static let warmup_sing_result_subtile = "You have completed your vocal warm-up!"
    static let warmup_sing_pitch_accuracy = "Pitch Accuracy"
    static let warmup_sing_test_again = "Warm-up Again"

    // MARK: - Pitch_train_intro
    static let pitch_train_intro_title = "Pitch Ear Training"
    static let pitch_train_intro_subtitle = "Identify single notes by name as you listen to them. For best results, practice daily"
    static let pitch_train_intro_select_level = "Select Difficulty Level"
    static let pitch_train_intro_level_easy = "Easy"
    static let pitch_train_intro_level_medium = "Medium"
    static let pitch_train_intro_level_hard = "Hard"

    // MARK: - Pitch_train
    static let pitch_train_select_notes = "Select the notes you heard"
    static let pitch_train_is_correct = "Nice!\"%@\" is correct!"
    static let pitch_train_not_correct = "\"%@\" is not correct"
    static let pitch_train_accuracy = "Pitch Accuracy"
    static let pitch_train_finished = "Finished !"
    static let pitch_train_summary_prefix = "You identified "
    static let pitch_train_summary_suffix = " of 10 correctly, Keep practicing !"
    static let pitch_train_hear_again = "Hear Again"
    static let pitch_train_train_again = "Training Again"

    // MARK: - Exit_popup
    static let exit_popup_title = "Are you sure to leave now?"
    static let exit_popup_resume = "Resume"
    static let exit_popup_exit = "Exit"
    static let exit_popup_restart = "Restart"

    // MARK: - Change_range
    static let change_range_song_range = "Song Range"
    static let change_range_your_voice = "Your Voice"
    static let change_range_original = "Original"
    static let change_range_your_range = "Your Vocal Range"
    static let change_range_best_fit = "Best Fit"
    static let change_range_save = "Save Range"

}
