//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct AquariumSpeciesResponseEntityModel: APIModel {
    public var id: Int64

    public var commonName: String

    public var mainImageUrl: String?

    public var scientificName: String?

    public var dataUrl: String?

    public var type: String

    public var count: Int

    public var identifyRecordId: Int64?

    enum CodingKeys: String, CodingKey {
        case id = "id"

        case commonName = "common_name"

        case mainImageUrl = "main_image_url"

        case scientificName = "scientific_name"

        case dataUrl = "data_url"

        case type = "type"

        case count = "count"

        case identifyRecordId = "identify_record_id"
    }
    
    public init(
            id: Int64, 
            commonName: String, 
            mainImageUrl: String? = nil, 
            scientificName: String? = nil, 
            dataUrl: String? = nil, 
            type: String, 
            count: Int, 
            identifyRecordId: Int64? = nil) {
        self.id = id
        self.commonName = commonName
        self.mainImageUrl = mainImageUrl
        self.scientificName = scientificName
        self.dataUrl = dataUrl
        self.type = type
        self.count = count
        self.identifyRecordId = identifyRecordId
    }
}
