//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct AquariumRequestEntityModel: APIModel {
    public var name: String

    public var coverImageUrl: String?

    public var size: String

    public var type: String

    public var careInfo: CareInfoRequestEntityModel?

    public var speciesList: [AquariumSpeciesRequestEntityModel]

    enum CodingKeys: String, CodingKey {
        case name = "name"

        case coverImageUrl = "cover_image_url"

        case size = "size"

        case type = "type"

        case careInfo = "care_info"

        case speciesList = "species_list"
    }
    
    public init(
            name: String, 
            coverImageUrl: String? = nil, 
            size: String, 
            type: String, 
            careInfo: CareInfoRequestEntityModel? = nil, 
            speciesList: [AquariumSpeciesRequestEntityModel]) {
        self.name = name
        self.coverImageUrl = coverImageUrl
        self.size = size
        self.type = type
        self.careInfo = careInfo
        self.speciesList = speciesList
    }
}
