//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct AquariumSpeciesRequestEntityModel: APIModel {
    public var commonName: String

    public var mainImageUrl: String

    public var scientificName: String

    public var dataUrl: String

    public var type: String

    public var count: Int

    public var identifyRecord: IdentifyRecordRequestEntityModel?

    enum CodingKeys: String, CodingKey {
        case commonName = "common_name"

        case mainImageUrl = "main_image_url"

        case scientificName = "scientific_name"

        case dataUrl = "data_url"

        case type = "type"

        case count = "count"

        case identifyRecord = "identify_record"
    }
    
    public init(
            commonName: String, 
            mainImageUrl: String, 
            scientificName: String, 
            dataUrl: String, 
            type: String, 
            count: Int, 
            identifyRecord: IdentifyRecordRequestEntityModel? = nil) {
        self.commonName = commonName
        self.mainImageUrl = mainImageUrl
        self.scientificName = scientificName
        self.dataUrl = dataUrl
        self.type = type
        self.count = count
        self.identifyRecord = identifyRecord
    }
}
