//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct CareInfoWaterGuideEntityModel: APIModel {
    public var changeFrequencyInfo: String

    public var checkInfo: String

    public var feedingInfo: String

    public var hardnessInfo: String

    public var phRangeInfo: String

    public var temperatureRangeInfo: String

    enum CodingKeys: String, CodingKey {
        case changeFrequencyInfo = "change_frequency_info"

        case checkInfo = "check_info"

        case feedingInfo = "feeding_info"

        case hardnessInfo = "hardness_info"

        case phRangeInfo = "ph_range_info"

        case temperatureRangeInfo = "temperature_range_info"
    }
    
    public init(
            changeFrequencyInfo: String, 
            checkInfo: String, 
            feedingInfo: String, 
            hardnessInfo: String, 
            phRangeInfo: String, 
            temperatureRangeInfo: String) {
        self.changeFrequencyInfo = changeFrequencyInfo
        self.checkInfo = checkInfo
        self.feedingInfo = feedingInfo
        self.hardnessInfo = hardnessInfo
        self.phRangeInfo = phRangeInfo
        self.temperatureRangeInfo = temperatureRangeInfo
    }
}
