//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct CareInfoRequestEntityModel: APIModel {
    public var score: Int

    public var guideTips: String

    public var compatibilityInfo: String

    public var waterGuide: CareInfoWaterGuideEntityModel

    enum CodingKeys: String, CodingKey {
        case score = "score"

        case guideTips = "guide_tips"

        case compatibilityInfo = "compatibility_info"

        case waterGuide = "water_guide"
    }
    
    public init(
            score: Int, 
            guideTips: String, 
            compatibilityInfo: String, 
            waterGuide: CareInfoWaterGuideEntityModel) {
        self.score = score
        self.guideTips = guideTips
        self.compatibilityInfo = compatibilityInfo
        self.waterGuide = waterGuide
    }
}
