//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct ChatHistoryRequestEntityModel: APIModel {
    public var sessionId: Int64

    public var scene: String

    public var lastMessage: String?

    enum CodingKeys: String, CodingKey {
        case sessionId = "session_id"

        case scene = "scene"

        case lastMessage = "last_message"
    }
    
    public init(
            sessionId: Int64, 
            scene: String, 
            lastMessage: String? = nil) {
        self.sessionId = sessionId
        self.scene = scene
        self.lastMessage = lastMessage
    }
}
