//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct IdentifyRecordRequestEntityModel: APIModel {
    public var uuid: String

    public var imageUrl: String

    public var scientificName: String?

    public var commonName: String?

    public var type: String

    public var generated: Bool

    public var breifContent: String?

    public var varieties: String?

    public var dataUrl: String?

    enum CodingKeys: String, CodingKey {
        case uuid = "uuid"

        case imageUrl = "image_url"

        case scientificName = "scientific_name"

        case commonName = "common_name"

        case type = "type"

        case generated = "generated"

        case breifContent = "breif_content"

        case varieties = "varieties"

        case dataUrl = "data_url"
    }
    
    public init(
            uuid: String, 
            imageUrl: String, 
            scientificName: String? = nil, 
            commonName: String? = nil, 
            type: String, 
            generated: Bool, 
            breifContent: String? = nil, 
            varieties: String? = nil, 
            dataUrl: String? = nil) {
        self.uuid = uuid
        self.imageUrl = imageUrl
        self.scientificName = scientificName
        self.commonName = commonName
        self.type = type
        self.generated = generated
        self.breifContent = breifContent
        self.varieties = varieties
        self.dataUrl = dataUrl
    }
}
