//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct IdentifyRecordV2EntityModel: APIModel {
    public var id: Int64

    public var imageUrl: String

    public var scientificName: String

    public var commonName: String

    public var type: String

    public var dataUrl: String

    public var generated: Bool

    public var varieties: String?

    public var breifContent: String?

    enum CodingKeys: String, CodingKey {
        case id = "id"

        case imageUrl = "image_url"

        case scientificName = "scientific_name"

        case commonName = "common_name"

        case type = "type"

        case dataUrl = "data_url"

        case generated = "generated"

        case varieties = "varieties"

        case breifContent = "breif_content"
    }
    
    public init(
            id: Int64, 
            imageUrl: String, 
            scientificName: String, 
            commonName: String, 
            type: String, 
            dataUrl: String, 
            generated: Bool, 
            varieties: String? = nil, 
            breifContent: String? = nil) {
        self.id = id
        self.imageUrl = imageUrl
        self.scientificName = scientificName
        self.commonName = commonName
        self.type = type
        self.dataUrl = dataUrl
        self.generated = generated
        self.varieties = varieties
        self.breifContent = breifContent
    }
}
