//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct UserdataAddIdentifyRecordRequest: APIEncodableRequest {
    public typealias Response = UserdataAddIdentifyRecordResponse

    public var identifyRecord: IdentifyRecordV2EntityModel

    enum CodingKeys: String, CodingKey {
        case identifyRecord = "identify_record"
    }
    
    public init(
            identifyRecord: IdentifyRecordV2EntityModel) {
        self.identifyRecord = identifyRecord
    }
    
    public var api: String {
        "v3/userdata/add_identify_record"
    }
    
    public var forceHttps: Bool {
        true
    }
    
    public var needAuth: Bool {
        true
    }
    
    public var mustAuth: Bool {
        true
    }
    
    public var methods: [String] {
        ["POST"]
    }
    
    public var mimeBodies: [APIMimeBody] {
        var bodies: [APIMimeBody] = []

        return bodies
    }
    
    public func parseParamater<T>(encoder: T) throws -> T.Output where T : APIEncoder {
        try encoder.encode(self)
    }
}

public struct UserdataAddIdentifyRecordResponse: APIJSONResponse {
    public var identifyRecordId: Int64

    enum CodingKeys: String, CodingKey {
        case identifyRecordId = "identify_record_id"
    }

    public init<T>(data: T.Input, decoder: T) throws where T : APIDecoder {
        self = try decoder.decode(UserdataAddIdentifyRecordResponse.self, from: data)
    }
}
