//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct UserdataGetIdentifyRecordListRequest: APIEncodableRequest {
    public typealias Response = UserdataGetIdentifyRecordListResponse

    
    public init(
            ) {
    }
    
    public var api: String {
        "v3/userdata/get_identify_record_list"
    }
    
    public var forceHttps: Bool {
        true
    }
    
    public var needAuth: Bool {
        true
    }
    
    public var mustAuth: Bool {
        true
    }
    
    public var methods: [String] {
        ["GET"]
    }
    
    public var mimeBodies: [APIMimeBody] {
        var bodies: [APIMimeBody] = []

        return bodies
    }
    
    public func parseParamater<T>(encoder: T) throws -> T.Output where T : APIEncoder {
        try encoder.encode(self)
    }
}

public struct UserdataGetIdentifyRecordListResponse: APIJSONResponse {
    public var identifyRecordList: [IdentifyRecordV2EntityModel]

    enum CodingKeys: String, CodingKey {
        case identifyRecordList = "identify_record_list"
    }

    public init<T>(data: T.Input, decoder: T) throws where T : APIDecoder {
        self = try decoder.decode(UserdataGetIdentifyRecordListResponse.self, from: data)
    }
}
