//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct UserdataGetUserAquariumDetailRequest: APIEncodableRequest {
    public typealias Response = UserdataGetUserAquariumDetailResponse

    public var aquariumId: Int64

    enum CodingKeys: String, CodingKey {
        case aquariumId = "aquarium_id"
    }
    
    public init(
            aquariumId: Int64) {
        self.aquariumId = aquariumId
    }
    
    public var api: String {
        "v3/userdata/get_user_aquarium_detail"
    }
    
    public var forceHttps: Bool {
        true
    }
    
    public var needAuth: Bool {
        true
    }
    
    public var mustAuth: Bool {
        true
    }
    
    public var methods: [String] {
        ["GET"]
    }
    
    public var mimeBodies: [APIMimeBody] {
        var bodies: [APIMimeBody] = []

        return bodies
    }
    
    public func parseParamater<T>(encoder: T) throws -> T.Output where T : APIEncoder {
        try encoder.encode(self)
    }
}

public struct UserdataGetUserAquariumDetailResponse: APIJSONResponse {
    public var aquarium: UserAquariumResponseEntityModel

    enum CodingKeys: String, CodingKey {
        case aquarium = "aquarium"
    }

    public init<T>(data: T.Input, decoder: T) throws where T : APIDecoder {
        self = try decoder.decode(UserdataGetUserAquariumDetailResponse.self, from: data)
    }
}
