//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct UserdataMigrateV1Request: APIEncodableRequest {
    public typealias Response = UserdataMigrateV1Response

    public var aquariumList: [AquariumRequestEntityModel]

    public var identifyRecordList: [IdentifyRecordRequestEntityModel]

    public var chatHistoryList: [ChatHistoryRequestEntityModel]

    enum CodingKeys: String, CodingKey {
        case aquariumList = "aquarium_list"

        case identifyRecordList = "identify_record_list"

        case chatHistoryList = "chat_history_list"
    }
    
    public init(
            aquariumList: [AquariumRequestEntityModel], 
            identifyRecordList: [IdentifyRecordRequestEntityModel], 
            chatHistoryList: [ChatHistoryRequestEntityModel]) {
        self.aquariumList = aquariumList
        self.identifyRecordList = identifyRecordList
        self.chatHistoryList = chatHistoryList
    }
    
    public var api: String {
        "v3/userdata/migrate_v1"
    }
    
    public var forceHttps: Bool {
        true
    }
    
    public var needAuth: Bool {
        true
    }
    
    public var mustAuth: Bool {
        true
    }
    
    public var methods: [String] {
        ["POST"]
    }
    
    public var mimeBodies: [APIMimeBody] {
        var bodies: [APIMimeBody] = []

        return bodies
    }
    
    public func parseParamater<T>(encoder: T) throws -> T.Output where T : APIEncoder {
        try encoder.encode(self)
    }
}

public struct UserdataMigrateV1Response: APIJSONResponse {
    public var success: Bool

    enum CodingKeys: String, CodingKey {
        case success = "success"
    }

    public init<T>(data: T.Input, decoder: T) throws where T : APIDecoder {
        self = try decoder.decode(UserdataMigrateV1Response.self, from: data)
    }
}
