//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct UserdataUpdateUserSpeciesCountRequest: APIEncodableRequest {
    public typealias Response = UserdataUpdateUserSpeciesCountResponse

    public var speciesId: Int64

    public var count: Int

    enum CodingKeys: String, CodingKey {
        case speciesId = "species_id"

        case count = "count"
    }
    
    public init(
            speciesId: Int64, 
            count: Int) {
        self.speciesId = speciesId
        self.count = count
    }
    
    public var api: String {
        "v3/userdata/update_user_species_count"
    }
    
    public var forceHttps: Bool {
        true
    }
    
    public var needAuth: Bool {
        true
    }
    
    public var mustAuth: Bool {
        true
    }
    
    public var methods: [String] {
        ["POST"]
    }
    
    public var mimeBodies: [APIMimeBody] {
        var bodies: [APIMimeBody] = []

        return bodies
    }
    
    public func parseParamater<T>(encoder: T) throws -> T.Output where T : APIEncoder {
        try encoder.encode(self)
    }
}

public struct UserdataUpdateUserSpeciesCountResponse: APIJSONResponse {
    public var success: Bool

    enum CodingKeys: String, CodingKey {
        case success = "success"
    }

    public init<T>(data: T.Input, decoder: T) throws where T : APIDecoder {
        self = try decoder.decode(UserdataUpdateUserSpeciesCountResponse.self, from: data)
    }
}
