//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct UserdataGetUserSpeciesDetailRequest: APIEncodableRequest {
    public typealias Response = UserdataGetUserSpeciesDetailResponse

    public var speciesId: Int64

    enum CodingKeys: String, CodingKey {
        case speciesId = "species_id"
    }
    
    public init(
            speciesId: Int64) {
        self.speciesId = speciesId
    }
    
    public var api: String {
        "v3/userdata/get_user_species_detail"
    }
    
    public var forceHttps: Bool {
        true
    }
    
    public var needAuth: Bool {
        true
    }
    
    public var mustAuth: Bool {
        true
    }
    
    public var methods: [String] {
        ["GET"]
    }
    
    public var mimeBodies: [APIMimeBody] {
        var bodies: [APIMimeBody] = []

        return bodies
    }
    
    public func parseParamater<T>(encoder: T) throws -> T.Output where T : APIEncoder {
        try encoder.encode(self)
    }
}

public struct UserdataGetUserSpeciesDetailResponse: APIJSONResponse {
    public var species: AquariumSpeciesResponseEntityModel

    enum CodingKeys: String, CodingKey {
        case species = "species"
    }

    public init<T>(data: T.Input, decoder: T) throws where T : APIDecoder {
        self = try decoder.decode(UserdataGetUserSpeciesDetailResponse.self, from: data)
    }
}
