//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct UserAquariumResponseEntityModel: APIModel {
    public var id: Int64

    public var name: String

    public var coverImageUrl: String?

    public var size: String

    public var type: String

    public var careInfoId: Int64?

    public var speciesCount: Int

    public var fishCount: Int

    public var chatSession: Int64?

    public var careInfo: CareInfoRequestEntityModel?

    public var speciesList: [AquariumSpeciesResponseEntityModel]?

    enum CodingKeys: String, CodingKey {
        case id = "id"

        case name = "name"

        case coverImageUrl = "cover_image_url"

        case size = "size"

        case type = "type"

        case careInfoId = "care_info_id"

        case speciesCount = "species_count"

        case fishCount = "fish_count"

        case chatSession = "chat_session"

        case careInfo = "care_info"

        case speciesList = "species_list"
    }
    
    public init(
            id: Int64, 
            name: String, 
            coverImageUrl: String? = nil, 
            size: String, 
            type: String, 
            careInfoId: Int64? = nil, 
            speciesCount: Int, 
            fishCount: Int, 
            chatSession: Int64? = nil, 
            careInfo: CareInfoRequestEntityModel? = nil, 
            speciesList: [AquariumSpeciesResponseEntityModel]? = nil) {
        self.id = id
        self.name = name
        self.coverImageUrl = coverImageUrl
        self.size = size
        self.type = type
        self.careInfoId = careInfoId
        self.speciesCount = speciesCount
        self.fishCount = fishCount
        self.chatSession = chatSession
        self.careInfo = careInfo
        self.speciesList = speciesList
    }
}
