//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public struct UserAquariumUpdateRequestEntityModel: APIModel {
    public var name: String?

    public var coverImageUrl: String?

    public var size: String?

    public var type: String?

    public var chatSession: Int64?

    enum CodingKeys: String, CodingKey {
        case name = "name"

        case coverImageUrl = "cover_image_url"

        case size = "size"

        case type = "type"

        case chatSession = "chat_session"
    }
    
    public init(
            name: String? = nil, 
            coverImageUrl: String? = nil, 
            size: String? = nil, 
            type: String? = nil, 
            chatSession: Int64? = nil) {
        self.name = name
        self.coverImageUrl = coverImageUrl
        self.size = size
        self.type = type
        self.chatSession = chatSession
    }
}
