//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI
import GLComponentAPI

/**
 * 删除业务数据
 */

public struct BizstorageDeleteStorageRequest: APIEncodableRequest {
    public typealias Response = BizstorageDeleteStorageResponse

    /**
     * storage id
     */
    public var storageId: Int64

    enum CodingKeys: String, CodingKey {
        case storageId = "storage_id"
    }
    
    public init(
            storageId: Int64) {
        self.storageId = storageId
    }
    
    public var api: String {
        "v1/bizstorage/delete_storage"
    }
    
    public var forceHttps: Bool {
        true
    }
    
    public var needAuth: Bool {
        true
    }
    
    public var mustAuth: Bool {
        true
    }
    
    public var methods: [String] {
        ["POST"]
    }
    
    public var mimeBodies: [APIMimeBody] {
        var bodies: [APIMimeBody] = []

        return bodies
    }
    
    public func parseParamater<T>(encoder: T) throws -> T.Output where T : APIEncoder {
        try encoder.encode(self)
    }
}

public struct BizstorageDeleteStorageResponse: APIJSONResponse {


    public init<T>(data: T.Input, decoder: T) throws where T : APIDecoder {
        self = try decoder.decode(BizstorageDeleteStorageResponse.self, from: data)
    }
}
