//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI
import GLComponentAPI

/**
 * 根据id查询业务数据
 */

public struct BizstorageGetStorageByIdRequest: APIEncodableRequest {
    public typealias Response = BizstorageGetStorageByIdResponse

    /**
     * 查询参数：storage id
     */
    public var storageId: Int64

    enum CodingKeys: String, CodingKey {
        case storageId = "storage_id"
    }
    
    public init(
            storageId: Int64) {
        self.storageId = storageId
    }
    
    public var api: String {
        "v1/bizstorage/get_storage_by_id"
    }
    
    public var forceHttps: Bool {
        true
    }
    
    public var needAuth: Bool {
        true
    }
    
    public var mustAuth: Bool {
        true
    }
    
    public var methods: [String] {
        ["GET"]
    }
    
    public var mimeBodies: [APIMimeBody] {
        var bodies: [APIMimeBody] = []

        return bodies
    }
    
    public func parseParamater<T>(encoder: T) throws -> T.Output where T : APIEncoder {
        try encoder.encode(self)
    }
}

public struct BizstorageGetStorageByIdResponse: APIJSONResponse {
    /**
     * 查询结果
     */
    public var storage: BizStorageModel

    enum CodingKeys: String, CodingKey {
        case storage = "storage"
    }

    public init<T>(data: T.Input, decoder: T) throws where T : APIDecoder {
        self = try decoder.decode(BizstorageGetStorageByIdResponse.self, from: data)
    }
}
