//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI
import GLComponentAPI

/**
 * 创建业务数据
 */

public struct BizstorageSaveStorageRequest: APIEncodableRequest {
    public typealias Response = BizstorageSaveStorageResponse

    /**
     * 业务数据类型
     */
    public var bizType: String

    /**
     * 待保存的业务数据
     */
    public var data: String

    enum CodingKeys: String, CodingKey {
        case bizType = "biz_type"

        case data = "data"
    }
    
    public init(
            bizType: String, 
            data: String) {
        self.bizType = bizType
        self.data = data
    }
    
    public var api: String {
        "v1/bizstorage/save_storage"
    }
    
    public var forceHttps: Bool {
        true
    }
    
    public var needAuth: Bool {
        true
    }
    
    public var mustAuth: Bool {
        true
    }
    
    public var methods: [String] {
        ["POST"]
    }
    
    public var mimeBodies: [APIMimeBody] {
        var bodies: [APIMimeBody] = []

        return bodies
    }
    
    public func parseParamater<T>(encoder: T) throws -> T.Output where T : APIEncoder {
        try encoder.encode(self)
    }
}

public struct BizstorageSaveStorageResponse: APIJSONResponse {
    /**
     * 保存的storage id *
     */
    public var storageId: Int64

    enum CodingKeys: String, CodingKey {
        case storageId = "storage_id"
    }

    public init<T>(data: T.Input, decoder: T) throws where T : APIDecoder {
        self = try decoder.decode(BizstorageSaveStorageResponse.self, from: data)
    }
}
