//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI
import GLComponentAPI

/**
 * 更新业务数据
 */

public struct BizstorageUpdateStorageRequest: APIEncodableRequest {
    public typealias Response = BizstorageUpdateStorageResponse

    /**
     * storage id
     */
    public var storageId: Int64

    /**
     * 待更新的业务数据
     */
    public var data: String

    enum CodingKeys: String, CodingKey {
        case storageId = "storage_id"

        case data = "data"
    }
    
    public init(
            storageId: Int64, 
            data: String) {
        self.storageId = storageId
        self.data = data
    }
    
    public var api: String {
        "v1/bizstorage/update_storage"
    }
    
    public var forceHttps: Bool {
        true
    }
    
    public var needAuth: Bool {
        true
    }
    
    public var mustAuth: Bool {
        true
    }
    
    public var methods: [String] {
        ["POST"]
    }
    
    public var mimeBodies: [APIMimeBody] {
        var bodies: [APIMimeBody] = []

        return bodies
    }
    
    public func parseParamater<T>(encoder: T) throws -> T.Output where T : APIEncoder {
        try encoder.encode(self)
    }
}

public struct BizstorageUpdateStorageResponse: APIJSONResponse {


    public init<T>(data: T.Input, decoder: T) throws where T : APIDecoder {
        self = try decoder.decode(BizstorageUpdateStorageResponse.self, from: data)
    }
}
