//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI
import GLComponentAPI

/**
 * 根据业务数据类型分页查询业务数据
 */

public struct BizstorageListStoragesRequest: APIEncodableRequest {
    public typealias Response = BizstorageListStoragesResponse

    /**
     * 查询参数：业务数据类型
     */
    public var bizType: String

    /**
     * 查询参数：本次查询返回的最后一个id，首次查询可为空
     */
    public var lastId: Int64?

    /**
     * 查询参数：每页大小
     */
    public var pageSize: Int?

    enum CodingKeys: String, CodingKey {
        case bizType = "biz_type"

        case lastId = "last_id"

        case pageSize = "page_size"
    }
    
    public init(
            bizType: String, 
            lastId: Int64? = nil, 
            pageSize: Int? = nil) {
        self.bizType = bizType
        self.lastId = lastId
        self.pageSize = pageSize
    }
    
    public var api: String {
        "v1/bizstorage/list_storages"
    }
    
    public var forceHttps: Bool {
        true
    }
    
    public var needAuth: Bool {
        true
    }
    
    public var mustAuth: Bool {
        true
    }
    
    public var methods: [String] {
        ["GET"]
    }
    
    public var mimeBodies: [APIMimeBody] {
        var bodies: [APIMimeBody] = []

        return bodies
    }
    
    public func parseParamater<T>(encoder: T) throws -> T.Output where T : APIEncoder {
        try encoder.encode(self)
    }
}

public struct BizstorageListStoragesResponse: APIJSONResponse {
    /**
     * 查询结果
     */
    public var list: [BizStorageModel]

    /**
     * 查询结果：总数
     */
    public var total: Int

    enum CodingKeys: String, CodingKey {
        case list = "list"

        case total = "total"
    }

    public init<T>(data: T.Input, decoder: T) throws where T : APIDecoder {
        self = try decoder.decode(BizstorageListStoragesResponse.self, from: data)
    }
}
