//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI
import GLComponentAPI

public struct BizStorageModel: APIModel {
    /**
     * storage id
     */
    public var storageId: Int64

    /**
     * user id
     */
    public var userId: Int64

    /**
     * 业务数据类型
     */
    public var bizType: String

    /**
     * 业务数据
     */
    public var data: String

    /**
     * 创建时间
     */
    public var createdAt: Date

    /**
     * 更新时间
     */
    public var updatedAt: Date

    enum CodingKeys: String, CodingKey {
        case storageId = "storage_id"

        case userId = "user_id"

        case bizType = "biz_type"

        case data = "data"

        case createdAt = "created_at"

        case updatedAt = "updated_at"
    }
    
    public init(
            storageId: Int64, 
            userId: Int64, 
            bizType: String, 
            data: String, 
            createdAt: Date, 
            updatedAt: Date) {
        self.storageId = storageId
        self.userId = userId
        self.bizType = bizType
        self.data = data
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
}
