//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI
import GLComponentAPI

/**
 * 获取任务信息以及结果文件
 */

public struct PdfextractorGetTaskByIdRequest: APIEncodableRequest {
    public typealias Response = PdfextractorGetTaskByIdResponse

    /**
     * 任务ID
     */
    public var taskId: String

    enum CodingKeys: String, CodingKey {
        case taskId = "task_id"
    }
    
    public init(
            taskId: String) {
        self.taskId = taskId
    }
    
    public var api: String {
        "v1/pdfextractor/get_task_by_id"
    }
    
    public var forceHttps: Bool {
        true
    }
    
    public var needAuth: Bool {
        true
    }
    
    public var mustAuth: Bool {
        true
    }
    
    public var methods: [String] {
        ["GET"]
    }
    
    public var mimeBodies: [APIMimeBody] {
        var bodies: [APIMimeBody] = []

        return bodies
    }
    
    public func parseParamater<T>(encoder: T) throws -> T.Output where T : APIEncoder {
        try encoder.encode(self)
    }
}

public struct PdfextractorGetTaskByIdResponse: APIJSONResponse {
    /**
     * 任务详情
     */
    public var task: TaskModel

    enum CodingKeys: String, CodingKey {
        case task = "task"
    }

    public init<T>(data: T.Input, decoder: T) throws where T : APIDecoder {
        self = try decoder.decode(PdfextractorGetTaskByIdResponse.self, from: data)
    }
}
