//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI
import GLComponentAPI

/**
 * 任务信息
 */
public struct TaskModel: APIModel {
    /**
     * 任务ID
     */
    public var taskId: String

    /**
     * 任务类型
     */
    public var processType: ProcessType

    /**
     * 任务状态
     */
    public var status: TaskStatus

    /**
     * 结果输出类型
     */
    public var outputFileFormat: OutputFileFormat

    /**
     * 文本检测结果，纯文本返回，需要调用方根据OutputFileFormat来决定怎么解析这部分文件
     */
    public var resultText: String?

    /**
     * 任务执行情况描述
     */
    public var message: String?

    enum CodingKeys: String, CodingKey {
        case taskId = "task_id"

        case processType = "process_type"

        case status = "status"

        case outputFileFormat = "output_file_format"

        case resultText = "result_text"

        case message = "message"
    }
    
    public init(
            taskId: String, 
            processType: ProcessType, 
            status: TaskStatus, 
            outputFileFormat: OutputFileFormat, 
            resultText: String? = nil, 
            message: String? = nil) {
        self.taskId = taskId
        self.processType = processType
        self.status = status
        self.outputFileFormat = outputFileFormat
        self.resultText = resultText
        self.message = message
    }
}
