//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

/**
 * 图片的宽高比
 */
public enum ImageAspectRatio: Int, APIEnumrable {
    /**
     * 1:1
     */
    case aspectRatio11 = 0

    /**
     * 9:16
     */
    case aspectRatio916 = 1

    /**
     * 16:9
     */
    case aspectRatio169 = 2

    /**
     * 3:4
     */
    case aspectRatio34 = 3

    /**
     * 4:3
     */
    case aspectRatio43 = 4
}
