//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public enum MessageType: Int, APIEnumrable, CaseIterable {
    case unknown = 0

    case text = 1

    case customize = 2

    case scene = 3

    case image = 4

    case imageList = 5

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let rawValue = try container.decode(Int.self)

        if let enumValue = MessageType(rawValue: rawValue) {
            self = enumValue
        } else if let enumValue = MessageType.allCases.first(where: { $0.rawValue == 0 }) {
            self = enumValue
        } else {
            let context = DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Cannot initialize MessageType from invalid Int value \(rawValue)")
            throw DecodingError.dataCorrupted(context)
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}
