//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

public enum OrderBy: Int, APIEnumrable, CaseIterable {
    case asc = 0

    case desc = 1

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let rawValue = try container.decode(Int.self)

        if let enumValue = OrderBy(rawValue: rawValue) {
            self = enumValue
        } else if let enumValue = OrderBy.allCases.first(where: { $0.rawValue == 0 }) {
            self = enumValue
        } else {
            let context = DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Cannot initialize OrderBy from invalid Int value \(rawValue)")
            throw DecodingError.dataCorrupted(context)
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}
