//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

/**
 * 输出的文件类型
 */
public enum OutputFileFormat: Int, APIEnumrable {
    /**
     * 纯文本
     */
    case plainText = 0

    /**
     * csv
     */
    case csv = 1

    /**
     * json
     */
    case json = 2
}
