//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

/**
 * 任务类型
 */
public enum ProcessType: Int, APIEnumrable {
    /**
     * 文档检测
     */
    case docDetection = 0

    /**
     * 文档分析
     */
    case docAnalysis = 1

    /**
     * 费用分析
     */
    case expenseAnalysis = 2
}
