//
//  this file is automatically generated, DO NOT MODIFY IT
//
//  Copyright © 2015 Glority. All rights reserved.
//

import Foundation
import DGMessageAPI

/**
 * 任务状态
 */
public enum TaskStatus: Int, APIEnumrable {
    /**
     * 新建，待执行
     */
    case new = 0

    /**
     * 执行中
     */
    case inProgress = 1

    /**
     * 执行成功
     */
    case success = 2

    /**
     * 执行失败
     */
    case failed = 3

    /**
     * 未知
     */
    case unknown = 100
}
