//
//  TrackingEvent.swift
//  AquaAI
//
//  Autogenerated by script. Do not modify manually.
//

import Foundation

typealias PageName = String

enum TrackingEvent: String {
  case home_newaqua_click
  case home_feedback_click
  case home_settings_click
  case home_tool_click
  case home_ask_click
  case home_aqua_click
  case home_addaqua_click
  case home_aquamore_click
  case home_aquadelete_click
  case createtank_type_click
  case createtank_size_click
  case createtank_save_click
  case createtank_back_click
  case createtank_close_click
  case aquadetail_takephoto_click
  case aquadetail_changecover_click
  case aquadetail_tab_click
  case aquadetail_newspecies_click
  case aquadetail_species_click
  case aquadetail_speciesmore_click
  case aquadetail_deletespecies_click
  case aquadetail_gettips_click
  case aquadetail_back_click
  case speciesdetail_save_click
  case speciesdetail_back_click
  case tankselect_close_click
  case tankselect_aqua_click
  case specieslist_tab_click
  case specieslist_search_click
  case specieslist_identify_click
  case specieslist_save_click
  case specieslist_item_click
  case specieslist_ask_click
  case speciessearch_item_click
  case speciessearch_save_click
  case speciessearch_cancel_click
  case history_search_click
  case history_tab_click
  case history_identifyitem_click
  case history_identifysave_click
  case history_camera_click
  case history_chatitem_click
  case history_chatmore_click
  case history_chatdelete_click
  case history_startchat_click
  case historysearch_item_click
  case historysearch_cancel_click
  case camera_type_click
  case camera_close_click
  case camera_guide_click
  case camera_torch_click
  case camera_switchcamera_click
  case camera_shot_click
  case camera_album_click
  case identify_close_click
  case identify_fail_click
  case identify_success_click
  case speciesdetailv2_back_click
  case speciesdetailv2_save_click
  case speciesdetailv2_rate_click
  case healthresult_back_click
  case healthresult_chat_click
  case setnumpopup_plus_click
  case setnumpopup_minus_click
  case setnumpopup_save_click
  case setnumpopup_back_click
  case changenumpopup_plus_click
  case changenumpopup_minus_click
  case changenumpopup_save_click
  case changenumpopup_back_click
  case aquaaddcart_back_click
  case aquaaddcart_addmore_click
  case aquaaddcart_save_click
  case aquaaddcart_more_click
  case aquaaddcart_delete_click
  case addaqualoading_close_click
  case addaqualoading_success_click
  case addaqualoading_fail_click
}

extension PageName {
  static let home = "home"
  static let createtank = "createtank"
  static let aquadetail = "aquadetail"
  static let speciesdetail = "speciesdetail"
  static let tankselect = "tankselect"
  static let specieslist = "specieslist"
  static let speciessearch = "speciessearch"
  static let history = "history"
  static let historysearch = "historysearch"
  static let camera = "camera"
  static let identify = "identify"
  static let speciesdetailv2 = "speciesdetailv2"
  static let healthresult = "healthresult"
  static let setnumpopup = "setnumpopup"
  static let changenumpopup = "changenumpopup"
  static let aquaaddcart = "aquaaddcart"
  static let addaqualoading = "addaqualoading"
}
